import {
  Armchair,
  Layers,
  Volume2,
  Music,
  UtensilsCrossed,
  GlassWater,
  Sparkles,
} from 'lucide-react';
import type { ServiceCategory } from './types';

export const serviceCategories: ServiceCategory[] = [
  {
    id: 'sillas-mesas',
    name: 'Sillas y Mesas',
    icon: Armchair,
    items: [
      {
        id: 'sillas-plasticas',
        name: 'Sillas plásticas',
        description: 'Silla plástica estándar para eventos.',
        price: 3500,
        unit: 'unidad',
      },
      {
        id: 'sillas-rimas',
        name: 'Sillas en rimas',
        description: 'Sillas apiladas, sin forro.',
        price: 4000,
        unit: 'unidad',
      },
      {
        id: 'forro-sillas',
        name: 'Forro para sillas',
        description: 'Cubre la silla para una mejor decoración.',
        price: 2000,
        unit: 'unidad',
      },
      {
        id: 'mesas-plasticas',
        name: 'Mesas plásticas',
        description: 'Mesa plástica redonda o rectangular.',
        price: 15000,
        unit: 'unidad',
      },
      {
        id: 'mesas-dobles',
        name: 'Mesas dobles',
        description: 'Mesa doble para mayor capacidad.',
        price: 25000,
        unit: 'unidad',
      },
      {
        id: 'mesas-rectangulares',
        name: 'Mesas rectangulares',
        description: 'Mesa rectangular para buffet o invitados.',
        price: 20000,
        unit: 'unidad',
      },
      {
        id: 'mesas-coctel',
        name: 'Mesas tipo cóctel',
        description: 'Mesas altas para áreas de socialización.',
        price: 18000,
        unit: 'unidad',
      },
      {
        id: 'manteles',
        name: 'Manteles',
        description: 'Mantelería básica para mesas.',
        price: 10000,
        unit: 'unidad',
      },
      {
        id: 'sobremanteles',
        name: 'Sobremanteles',
        description: 'Sobremantel decorativo de color.',
        price: 8000,
        unit: 'unidad',
      },
    ],
  },
  {
    id: 'tarimas',
    name: 'Tarimas',
    icon: Layers,
    items: [
      {
        id: 'tarima-basica',
        name: 'Tarima básica',
        description: 'Tarima estándar para presentaciones.',
        price: 300000,
        unit: 'paquete',
      },
      {
        id: 'tarima-reforzada',
        name: 'Tarima reforzada',
        description: 'Para equipos pesados o grupos grandes.',
        price: 500000,
        unit: 'paquete',
      },
      {
        id: 'tarima-dj',
        name: 'Tarima para DJ',
        description: 'Estructura elevada para el DJ.',
        price: 250000,
        unit: 'paquete',
      },
      {
        id: 'tarima-protocolo',
        name: 'Tarima para protocolo',
        description: 'Para ceremonias y actos oficiales.',
        price: 350000,
        unit: 'paquete',
      },
    ],
  },
  {
    id: 'sonido-iluminacion',
    name: 'Sonido e Iluminación',
    icon: Volume2,
    items: [
      {
        id: 'sonido-50-100',
        name: 'Sonido para 50 a 100 personas',
        description: 'Paquete básico de sonido y luces.',
        price: 1000000,
        unit: 'paquete',
      },
      {
        id: 'sonido-100-200',
        name: 'Sonido para 100 a 200 personas',
        description: 'Paquete intermedio de sonido y luces.',
        price: 1500000,
        unit: 'paquete',
      },
      {
        id: 'sonido-200-400',
        name: 'Sonido para 200 a 400 personas',
        description: 'Paquete avanzado de sonido y luces.',
        price: 2500000,
        unit: 'paquete',
      },
      {
        id: 'sonido-400-500',
        name: 'Sonido para 400 a 500 personas',
        description: 'Paquete profesional de sonido y luces.',
        price: 3500000,
        unit: 'paquete',
      },
      {
        id: 'sonido-800-1000',
        name: 'Sonido para 800 a 1000 personas',
        description: 'Paquete para grandes eventos.',
        price: 5000000,
        unit: 'paquete',
      },
    ],
  },
  {
    id: 'musica-animacion',
    name: 'Música y Animación',
    icon: Music,
    items: [
      {
        id: 'dj',
        name: 'DJ',
        description: 'DJ profesional para tu evento.',
        price: 900000,
        unit: 'paquete',
      },
      {
        id: 'animador',
        name: 'Animador',
        description: 'Para mantener la energía de la fiesta.',
        price: 700000,
        unit: 'paquete',
      },
      {
        id: 'maestro-ceremonias',
        name: 'Maestro de ceremonias',
        description: 'Conducción profesional del evento.',
        price: 800000,
        unit: 'paquete',
      },
      {
        id: 'grupo-musical',
        name: 'Grupo musical en vivo',
        description: 'Banda en vivo para tu fiesta.',
        price: 2500000,
        unit: 'paquete',
      },
    ],
  },
  {
    id: 'alimentacion',
    name: 'Alimentación',
    icon: UtensilsCrossed,
    items: [
      {
        id: 'plato-2-carnes',
        name: 'Plato fuerte 2 carnes',
        description: 'Plato principal con dos opciones de carne.',
        price: 45000,
        unit: 'persona',
      },
      {
        id: 'plato-3-carnes',
        name: 'Plato fuerte 3 carnes',
        description: 'Plato principal con tres opciones de carne.',
        price: 60000,
        unit: 'persona',
      },
      {
        id: 'menu-ejecutivo',
        name: 'Menú ejecutivo',
        description: 'Opción balanceada para eventos corporativos.',
        price: 35000,
        unit: 'persona',
      },
      {
        id: 'menu-infantil',
        name: 'Menú infantil',
        description: 'Plato especial para los más pequeños.',
        price: 25000,
        unit: 'persona',
      },
      {
        id: 'pasabocas-salados',
        name: 'Pasabocas salados',
        description: 'Variedad de snacks de sal.',
        price: 15000,
        unit: 'persona',
      },
      {
        id: 'pasabocas-dulces',
        name: 'Pasabocas dulces',
        description: 'Variedad de snacks de dulce.',
        price: 15000,
        unit: 'persona',
      },
      {
        id: 'mesa-postres',
        name: 'Mesa de postres',
        description: 'Estación con variedad de postres.',
        price: 400000,
        unit: 'paquete',
      },
      {
        id: 'pastel',
        name: 'Pastel',
        description: 'Pastel temático para la ocasión.',
        price: 800000,
        unit: 'paquete',
      },
      {
        id: 'refrigerios',
        name: 'Refrigerios',
        description: 'Opción ligera para pausas.',
        price: 12000,
        unit: 'persona',
      },
    ],
  },
  {
    id: 'bebidas',
    name: 'Bebidas',
    icon: GlassWater,
    items: [
      {
        id: 'gaseosa',
        name: 'Gaseosa',
        description: 'Gaseosa ilimitada durante el evento.',
        price: 7000,
        unit: 'persona',
      },
      {
        id: 'agua',
        name: 'Agua',
        description: 'Agua embotellada con y sin gas.',
        price: 3000,
        unit: 'persona',
      },
      {
        id: 'jugos-naturales',
        name: 'Jugos naturales',
        description: 'Variedad de jugos de fruta fresca.',
        price: 9000,
        unit: 'persona',
      },
      {
        id: 'bebidas-calientes',
        name: 'Bebidas calientes',
        description: 'Estación de café y aromáticas.',
        price: 5000,
        unit: 'persona',
      },
      {
        id: 'cocteles-sin-alcohol',
        name: 'Cócteles sin alcohol',
        description: 'Mocktails y coctelería sin licor.',
        price: 12000,
        unit: 'persona',
      },
      {
        id: 'whisky',
        name: 'Whisky (Botella)',
        description: 'Botella de Whisky de 700ml.',
        price: 120000,
        unit: 'unidad',
      },
    ],
  },
  {
    id: 'decoracion',
    name: 'Decoración',
    icon: Sparkles,
    items: [
      {
        id: 'decoracion-basica',
        name: 'Decoración básica',
        description: 'Decoración estándar para el salón.',
        price: 1000000,
        unit: 'paquete',
      },
      {
        id: 'decoracion-tematica',
        name: 'Decoración temática',
        description: 'Decoración personalizada según el tema.',
        price: 1800000,
        unit: 'paquete',
      },
      {
        id: 'decoracion-premium',
        name: 'Decoración premium',
        description: 'Diseño exclusivo y materiales de lujo.',
        price: 3000000,
        unit: 'paquete',
      },
      {
        id: 'centros-mesa',
        name: 'Centros de mesa',
        description: 'Arreglos decorativos para cada mesa.',
        price: 50000,
        unit: 'unidad',
      },
      {
        id: 'arco-globos',
        name: 'Arcos de globos',
        description: 'Estructura decorativa con globos.',
        price: 400000,
        unit: 'paquete',
      },
      {
        id: 'flores-naturales',
        name: 'Flores naturales',
        description: 'Arreglos florales para el evento.',
        price: 1500000,
        unit: 'paquete',
      },
      {
        id: 'letras-gigantes',
        name: 'Letras gigantes',
        description: 'Letras iluminadas (ej. "MIS 15").',
        price: 600000,
        unit: 'paquete',
      },
    ],
  },
];
